### ISSUE TITLE
Update plugins list

### ISSUE THREAD

**Issue by yoanmalie** [heroheman/kirby-directory#16]
Hi,
It look like there is no new referenced plugins since 15 days, I thinks it's because the repo maintainer have changed ? The URL to the repo is now https://github.com/texnixe/kirby-plugins

**Comment by mullema** [comment]
To keep this one running: The kirby.directory is still missing the latest plugins for Kirby 3

**Comment by heroheman** [comment]
Hey @yoanmalie  @mullema ,
sorry for the delay and thanks for the heads up. 
There is a bug right now that is messing with the data and the cronjob. I have right a new mayor version (1.3) in the works that should fix this issue (in fact the whole data handling should be a lot faster) but no release date right now - hopefully the next days. 

Until then I will manually start the data fetching cronjob every other day.
