### ISSUE TITLE
Encoding issue in readme

### ISSUE THREAD

**Issue by jenstornell** [heroheman/kirby-directory#4]
>Jens TÃ¶rnell

**Comment by heroheman** [comment]
I just realized that your name is not Tornell

**Comment by jenstornell** [comment]
Not "Tornell" and not "TÃ¶rnell". Maybe you will get it right some day. 😂😉

(Should be "Törnell") 👍

**Comment by heroheman** [comment]
there was a problem with `atob()`.
Fixed it with: https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_Unicode_Problem
