### ISSUE TITLE
Plugin image preview

### ISSUE THREAD

**Issue by jenstornell** [heroheman/kirby-directory#6]
Just an idea.

Not sure how hard it is but in the result list: Provide an image preview for each plugin that has it.

An image can sometimes be found in the plugin repo issue. I recommend to pick the first inside the issue content. Dont get it from the plugin readme because then you may fetch a logo or something etc.

**Comment by heroheman** [comment]
This is not so easy to implement.
I could just take the first image, but some the images have a huge filesize. Before that I need some kind of optimization. 
There isn't much Backend. In fact none. 

Maybe scan my json file for images, curl them and resize the images on the serverside with a cronjob.

Not sure maybe I can come up with something.

**Comment by heroheman** [comment]
If I default the list from 20 to 10, ignore the gifs and include some kind of lazyloading it may work. I will try!

**Comment by heroheman** [comment]
ok, tried out and it just works fine. 
![screenshot from 2018-08-12 12 28 39](https://user-images.githubusercontent.com/407485/44001080-638ed570-9e2b-11e8-8dfa-79b128069c54.png)

The problem I face now is that all the screenshots have different dimensions. And most of them are showing a panel where you cant see a thing at all.

The clip-path (circles) are an attempt to make them consistent

**Comment by heroheman** [comment]
Done. Not sure when it will be on the server.
